services:
  proxy:
    image: docker.io/library/nginx:alpine
    volumes:
      - ./mock-api/nginx-template/:/etc/nginx/templates/:ro
    depends_on:
      - signalr

  signalr:
    image: docker.io/library/python:3.12
    volumes:
      - ./mock-api/:/opt/
    environment:
      - REGEXP=${REGEXP}
    command:
      - /bin/sh
      - -c
      - >
        cd /opt &&
        python -m pip install -r requirements.txt && 
        gunicorn -b 0.0.0.0:8000 --workers 1 --threads 64 --log-level debug --reload signalr:app
  
  bot:
    image: docker.io/library/python:3.12
    volumes:
      - ./:/opt
    environment:
      - VERBOSE=${VERBOSE:-True}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - USE_SSL=${USE_SSL:-False}
      - API_HOST=${API_HOST:-proxy}
      - RETRY=${RETRY:-False}
      - VER_TAG=${CI_JOB_ID:-local}
    command:
      - /bin/sh
      - -c
      - >
        cd /opt &&
        python -m pip install -r requirements.txt &&
        sleep 10 &&
        python main.py
    depends_on:
      - proxy
    