services:
  proxy:
    image: docker.io/library/nginx:alpine
    privileged: true
    volumes:
      - ./mock-api/nginx-template/:/etc/nginx/templates/:Z
    depends_on:
      - signalr

  signalr:
    image: docker.io/library/python:3.12
    privileged: true
    volumes:
      - ./mock-api/:/opt/:Z
    environment:
      - SEASON=${SEASON:-2023}
      - MEETING=${MEETING}
      - SESSION=${SESSION}
      - MESSAGE_GAP=${MESSAGE_GAP:-5}
    command:
      - /bin/sh
      - -c
      - >
        cd /opt &&
        python -m pip install -r requirements.txt && 
        gunicorn -b 0.0.0.0:8000 --workers 1 --threads 64 --log-level debug --reload signalr:app
  
  bot:
    image: quay.io/rockylinux/rockylinux:8
    privileged: true
    volumes:
      - ./team-radio:/opt:Z
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - USE_SSL=${USE_SSL:-False}
      - API_HOST=${API_HOST:-proxy}
      - RETRY=${RETRY:-False}
      - VER_TAG=${CI_JOB_ID:-local}
    command:
      - /opt/run.sh
    depends_on:
      - proxy
    
