.deployment-config: &deployment-config
  image: quay.io/rockylinux/rockylinux:8
  stage: deploy
  before_script:
    - yum install -y epel-release
    - yum install -y ansible openssh-clients
    - mkdir -pv ~/.ssh/
    - cp ${SSH_KEY_PRI} ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - cp ${INVENTORY} ./inventory.ini
    - cp ${CONFIG} ./ansible.cfg
    - chmod -R g-w,o-w .

deploy-branch:
  <<: *deployment-config
  script:
    - BRANCH_GRP=$(echo ${CI_COMMIT_BRANCH} | cut -d'-' -f1)
    - ansible-playbook -l ${BRANCH_GRP} -e suffix=-${BRANCH_GRP} playbook/01-deploy.yml
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == 'true'

deploy-stable:
  <<: *deployment-config
  script:
    - ansible-playbook -l ${CI_COMMIT_BRANCH} playbook/01-deploy.yml
  rules:
    - if: $CI_COMMIT_TAG
