create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "Create release ${CI_COMMIT_TAG}"
    - echo "${CI_COMMIT_TAG_MESSAGE}"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG_MESSAGE'

release-job:
  stage: release
  image: quay.io/podman/stable
  script:
    - podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - podman pull "$CI_REGISTRY_IMAGE/race-control:$CI_COMMIT_SHORT_SHA"
    - podman tag "$CI_REGISTRY_IMAGE/race-control:$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_IMAGE/race-control:$CI_COMMIT_TAG" "$CI_REGISTRY_IMAGE/race-control:latest"
    - podman push "$CI_REGISTRY_IMAGE/race-control:$CI_COMMIT_TAG"
    - podman push "$CI_REGISTRY_IMAGE/race-control:latest"
  rules:
    - if: $CI_COMMIT_TAG